library("fitdistrplus")
df_file1_q6 <- read.csv("file1.csv_q6", header=TRUE)
plot(df_file1_q6$X)
plotdist(df_file1_q6$X, histo=TRUE, demp=TRUE)
descdist(df_file1_q6$X)

par(mfrow=c(2,2))
file1_q6_fe_exp <- fitdist(df_file1_q6$X, "exp")
denscomp(list(file1_q6_fe_exp), legendtext=c("exp"))
cdfcomp(list(file1_q6_fe_exp), legendtext=c("exp"))
qqcomp(list(file1_q6_fe_exp), legendtext=c("exp"))

par(mfrow=c(2,2))
file1_q6_fe_norm <- fitdist(df_file1_q6$X, "norm")
denscomp(list(file1_q6_fe_norm), legendtext=c("norm"))
cdfcomp(list(file1_q6_fe_norm), legendtext=c("norm"))
qqcomp(list(file1_q6_fe_norm), legendtext=c("norm"))

par(mfrow=c(2,2))
file1_q6_fe_lnorm <- fitdist(df_file1_q6$X, "lnorm")
denscomp(list(file1_q6_fe_lnorm), legendtext=c("lnorm"))
cdfcomp(list(file1_q6_fe_lnorm), legendtext=c("lnorm"))
qqcomp(list(file1_q6_fe_lnorm), legendtext=c("lnorm"))

par(mfrow=c(1,1))
df_file2_q6 <- read.csv("file2.csv_q6", header=TRUE)
plot(df_file2_q6$X)
plotdist(df_file2_q6$X, histo=TRUE, demp=TRUE)
descdist(df_file2_q6$X)

par(mfrow=c(2,2))
file2_q6_fe_exp <- fitdist(df_file2_q6$X, "exp")
denscomp(list(file2_q6_fe_exp), legendtext=c("exp"))
cdfcomp(list(file2_q6_fe_exp), legendtext=c("exp"))
qqcomp(list(file2_q6_fe_exp), legendtext=c("exp"))

par(mfrow=c(2,2))
file2_q6_fe_norm <- fitdist(df_file2_q6$X, "norm")
denscomp(list(file2_q6_fe_norm), legendtext=c("norm"))
cdfcomp(list(file2_q6_fe_norm), legendtext=c("norm"))
qqcomp(list(file2_q6_fe_norm), legendtext=c("norm"))

par(mfrow=c(2,2))
file2_q6_fe_lnorm <- fitdist(df_file2_q6$X, "lnorm")
denscomp(list(file2_q6_fe_lnorm), legendtext=c("lnorm"))
cdfcomp(list(file2_q6_fe_lnorm), legendtext=c("lnorm"))
qqcomp(list(file2_q6_fe_lnorm), legendtext=c("lnorm"))

par(mfrow=c(1,1))
df_file3_q6 <- read.csv("file3.csv_q6", header=TRUE)
plot(df_file3_q6$X)
plotdist(df_file3_q6$X, histo=TRUE, demp=TRUE)
descdist(df_file3_q6$X)

par(mfrow=c(2,2))
file3_q6_fe_exp <- fitdist(df_file3_q6$X, "exp")
denscomp(list(file3_q6_fe_exp), legendtext=c("exp"))
cdfcomp(list(file3_q6_fe_exp), legendtext=c("exp"))
qqcomp(list(file3_q6_fe_exp), legendtext=c("exp"))

par(mfrow=c(2,2))
file3_q6_fe_norm <- fitdist(df_file3_q6$X, "norm")
denscomp(list(file3_q6_fe_norm), legendtext=c("norm"))
cdfcomp(list(file3_q6_fe_norm), legendtext=c("norm"))
qqcomp(list(file3_q6_fe_norm), legendtext=c("norm"))

par(mfrow=c(2,2))
file3_q6_fe_lnorm <- fitdist(df_file3_q6$X, "lnorm")
denscomp(list(file3_q6_fe_lnorm), legendtext=c("lnorm"))
cdfcomp(list(file3_q6_fe_lnorm), legendtext=c("lnorm"))
qqcomp(list(file3_q6_fe_lnorm), legendtext=c("lnorm"))

par(mfrow=c(1,1))
df_file1_q7 <- read.csv("file1.csv_q7", header=TRUE)
plot(df_file1_q7$X)
plotdist(df_file1_q7$X, histo=TRUE, demp=TRUE)
descdist(df_file1_q7$X)

par(mfrow=c(2,2))
file1_q7_fe_exp <- fitdist(df_file1_q7$X, "exp")
file1_q7_fe_exp
denscomp(list(file1_q7_fe_exp), legendtext=c("exp"))
cdfcomp(list(file1_q7_fe_exp), legendtext=c("exp"))
qqcomp(list(file1_q7_fe_exp), legendtext=c("exp"))

par(mfrow=c(2,2))
file1_q7_fe_norm <- fitdist(df_file1_q7$X, "norm")
denscomp(list(file1_q7_fe_norm), legendtext=c("norm"))
cdfcomp(list(file1_q7_fe_norm), legendtext=c("norm"))
qqcomp(list(file1_q7_fe_norm), legendtext=c("norm"))

par(mfrow=c(2,2))
file1_q7_fe_lnorm <- fitdist(df_file1_q7$X, "lnorm")
denscomp(list(file1_q7_fe_lnorm), legendtext=c("lnorm"))
cdfcomp(list(file1_q7_fe_lnorm), legendtext=c("lnorm"))
qqcomp(list(file1_q7_fe_lnorm), legendtext=c("lnorm"))

par(mfrow=c(1,1))
df_file2_q7 <- read.csv("file2.csv_q7", header=TRUE)
plot(df_file2_q7$X)
plotdist(df_file2_q7$X, histo=TRUE, demp=TRUE)
descdist(df_file2_q7$X)

par(mfrow=c(2,2))
file2_q7_fe_exp <- fitdist(df_file2_q7$X, "exp")
file2_q7_fe_exp
denscomp(list(file2_q7_fe_exp), legendtext=c("exp"))
cdfcomp(list(file2_q7_fe_exp), legendtext=c("exp"))
qqcomp(list(file2_q7_fe_exp), legendtext=c("exp"))

par(mfrow=c(2,2))
file2_q7_fe_norm <- fitdist(df_file2_q7$X, "norm")
denscomp(list(file2_q7_fe_norm), legendtext=c("norm"))
cdfcomp(list(file2_q7_fe_norm), legendtext=c("norm"))
qqcomp(list(file2_q7_fe_norm), legendtext=c("norm"))

par(mfrow=c(2,2))
file2_q7_fe_lnorm <- fitdist(df_file2_q7$X, "lnorm")
denscomp(list(file2_q7_fe_lnorm), legendtext=c("lnorm"))
cdfcomp(list(file2_q7_fe_lnorm), legendtext=c("lnorm"))
qqcomp(list(file2_q7_fe_lnorm), legendtext=c("lnorm"))

par(mfrow=c(1,1))
df_file3_q7 <- read.csv("file3.csv_q7", header=TRUE)
plot(df_file3_q7$X)
plotdist(df_file3_q7$X, histo=TRUE, demp=TRUE)
descdist(df_file3_q7$X)

par(mfrow=c(2,2))
file3_q7_fe_exp <- fitdist(df_file3_q7$X, "exp")
file3_q7_fe_exp
denscomp(list(file3_q7_fe_exp), legendtext=c("exp"))
cdfcomp(list(file3_q7_fe_exp), legendtext=c("exp"))
qqcomp(list(file3_q7_fe_exp), legendtext=c("exp"))

par(mfrow=c(2,2))
file3_q7_fe_norm <- fitdist(df_file3_q7$X, "norm")
denscomp(list(file3_q7_fe_norm), legendtext=c("norm"))
cdfcomp(list(file3_q7_fe_norm), legendtext=c("norm"))
qqcomp(list(file3_q7_fe_norm), legendtext=c("norm"))

par(mfrow=c(2,2))
file3_q7_fe_lnorm <- fitdist(df_file3_q7$X, "lnorm")
denscomp(list(file3_q7_fe_lnorm), legendtext=c("lnorm"))
cdfcomp(list(file3_q7_fe_lnorm), legendtext=c("lnorm"))
qqcomp(list(file3_q7_fe_lnorm), legendtext=c("lnorm"))